# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools/v1/tools.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tools/v1/tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tools/v1/tools.proto\x12\x17\x61rangodb.cloud.tools.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16\x63ommon/v1/common.proto\"S\n\x0cToolsVersion\x12\x16\n\x0elatest_version\x18\x01 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x02 \x01(\t\x12\x15\n\ris_compatible\x18\x03 \x01(\x08\"o\n\x17GetLatestVersionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x46\n\x15\x65xpected_api_versions\x18\x02 \x03(\x0b\x32\'.arangodb.cloud.tools.v1.APIVersionPair\"T\n\x0e\x41PIVersionPair\x12\x0e\n\x06\x61pi_id\x18\x01 \x01(\t\x12\x32\n\x07version\x18\x02 \x01(\x0b\x32!.arangodb.cloud.common.v1.Version2\x9a\x02\n\x0cToolsService\x12v\n\rGetAPIVersion\x12\x1f.arangodb.cloud.common.v1.Empty\x1a!.arangodb.cloud.common.v1.Version\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/tools/v1/api-version\x12\x91\x01\n\x10GetLatestVersion\x12\x30.arangodb.cloud.tools.v1.GetLatestVersionRequest\x1a%.arangodb.cloud.tools.v1.ToolsVersion\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/tools/v1/latest-versionB+Z)github.com/arangodb-managed/apis/tools/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.v1.tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/arangodb-managed/apis/tools/v1'
  _globals['_TOOLSSERVICE'].methods_by_name['GetAPIVersion']._loaded_options = None
  _globals['_TOOLSSERVICE'].methods_by_name['GetAPIVersion']._serialized_options = b'\202\323\344\223\002\033\022\031/api/tools/v1/api-version'
  _globals['_TOOLSSERVICE'].methods_by_name['GetLatestVersion']._loaded_options = None
  _globals['_TOOLSSERVICE'].methods_by_name['GetLatestVersion']._serialized_options = b'\202\323\344\223\002\036\022\034/api/tools/v1/latest-version'
  _globals['_TOOLSVERSION']._serialized_start=103
  _globals['_TOOLSVERSION']._serialized_end=186
  _globals['_GETLATESTVERSIONREQUEST']._serialized_start=188
  _globals['_GETLATESTVERSIONREQUEST']._serialized_end=299
  _globals['_APIVERSIONPAIR']._serialized_start=301
  _globals['_APIVERSIONPAIR']._serialized_end=385
  _globals['_TOOLSSERVICE']._serialized_start=388
  _globals['_TOOLSSERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
