# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from credits.v1 import credits_pb2 as credits_dot_v1_dot_credits__pb2


class CreditsServiceStub(object):
    """CreditsService is the API used for managing credits.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCreditBundles = channel.unary_unary(
                '/arangodb.cloud.credits.v1.CreditsService/ListCreditBundles',
                request_serializer=credits_dot_v1_dot_credits__pb2.ListCreditBundlesRequest.SerializeToString,
                response_deserializer=credits_dot_v1_dot_credits__pb2.CreditBundlesList.FromString,
                )


class CreditsServiceServicer(object):
    """CreditsService is the API used for managing credits.
    """

    def ListCreditBundles(self, request, context):
        """List credit bundles for an organization.
        Required permissions:
        - credit.creditbundle.list on the organization identified by the given organization ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreditsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCreditBundles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCreditBundles,
                    request_deserializer=credits_dot_v1_dot_credits__pb2.ListCreditBundlesRequest.FromString,
                    response_serializer=credits_dot_v1_dot_credits__pb2.CreditBundlesList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arangodb.cloud.credits.v1.CreditsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreditsService(object):
    """CreditsService is the API used for managing credits.
    """

    @staticmethod
    def ListCreditBundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.credits.v1.CreditsService/ListCreditBundles',
            credits_dot_v1_dot_credits__pb2.ListCreditBundlesRequest.SerializeToString,
            credits_dot_v1_dot_credits__pb2.CreditBundlesList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
