# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credits/v1/credits.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from github.com.golang.protobuf.ptypes.timestamp import timestamp_pb2 as github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_timestamp_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63redits/v1/credits.proto\x12\x19\x61rangodb.cloud.credits.v1\x1a\x16\x63ommon/v1/common.proto\x1a;github.com/golang/protobuf/ptypes/timestamp/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"L\n\x18ListCreditBundlesRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x17\n\x0f\x65xclude_expired\x18\x02 \x01(\x08\"K\n\x11\x43reditBundlesList\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.arangodb.cloud.credits.v1.CreditBundle\"\xb0\x02\n\x0c\x43reditBundle\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x04 \x01(\t\x12\x19\n\x11\x63redits_purchased\x18\x05 \x01(\x02\x12\x13\n\x0btotal_price\x18\x06 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x19\n\x11\x63redits_remaining\x18\x08 \x01(\x02\x12\x30\n\x0cpurchased_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nvalid_from\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bvalid_until\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc2\x01\n\x0e\x43reditsService\x12\xaf\x01\n\x11ListCreditBundles\x12\x33.arangodb.cloud.credits.v1.ListCreditBundlesRequest\x1a,.arangodb.cloud.credits.v1.CreditBundlesList\"7\x82\xd3\xe4\x93\x02\x31\x12//api/credits/v1/{organization_id}/creditbundlesB-Z+github.com/arangodb-managed/apis/credits/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credits.v1.credits_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+github.com/arangodb-managed/apis/credits/v1'
  _CREDITSSERVICE.methods_by_name['ListCreditBundles']._options = None
  _CREDITSSERVICE.methods_by_name['ListCreditBundles']._serialized_options = b'\202\323\344\223\0021\022//api/credits/v1/{organization_id}/creditbundles'
  _globals['_LISTCREDITBUNDLESREQUEST']._serialized_start=170
  _globals['_LISTCREDITBUNDLESREQUEST']._serialized_end=246
  _globals['_CREDITBUNDLESLIST']._serialized_start=248
  _globals['_CREDITBUNDLESLIST']._serialized_end=323
  _globals['_CREDITBUNDLE']._serialized_start=326
  _globals['_CREDITBUNDLE']._serialized_end=630
  _globals['_CREDITSSERVICE']._serialized_start=633
  _globals['_CREDITSSERVICE']._serialized_end=827
# @@protoc_insertion_point(module_scope)
