# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency/v1/currency.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63urrency/v1/currency.proto\x12\x1a\x61rangodb.cloud.currency.v1\x1a\x16\x63ommon/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"H\n\x08\x43urrency\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x14\n\x0ciso4217_code\x18\x04 \x01(\t\"C\n\x0c\x43urrencyList\x12\x33\n\x05items\x18\x01 \x03(\x0b\x32$.arangodb.cloud.currency.v1.Currency\"4\n\x19GetDefaultCurrencyRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\t2\xb9\x04\n\x0f\x43urrencyService\x12y\n\rGetAPIVersion\x12\x1f.arangodb.cloud.common.v1.Empty\x1a!.arangodb.cloud.common.v1.Version\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/currency/v1/api-version\x12\x86\x01\n\x0eListCurrencies\x12%.arangodb.cloud.common.v1.ListOptions\x1a(.arangodb.cloud.currency.v1.CurrencyList\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/currency/v1/currencies\x12\x82\x01\n\x0bGetCurrency\x12#.arangodb.cloud.common.v1.IDOptions\x1a$.arangodb.cloud.currency.v1.Currency\"(\x82\xd3\xe4\x93\x02\"\x12 /api/currency/v1/currencies/{id}\x12\x9c\x01\n\x12GetDefaultCurrency\x12\x35.arangodb.cloud.currency.v1.GetDefaultCurrencyRequest\x1a$.arangodb.cloud.currency.v1.Currency\")\x82\xd3\xe4\x93\x02#\x12!/api/currency/v1/default-currencyB.Z,github.com/arangodb-managed/apis/currency/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency.v1.currency_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/arangodb-managed/apis/currency/v1'
  _CURRENCYSERVICE.methods_by_name['GetAPIVersion']._options = None
  _CURRENCYSERVICE.methods_by_name['GetAPIVersion']._serialized_options = b'\202\323\344\223\002\036\022\034/api/currency/v1/api-version'
  _CURRENCYSERVICE.methods_by_name['ListCurrencies']._options = None
  _CURRENCYSERVICE.methods_by_name['ListCurrencies']._serialized_options = b'\202\323\344\223\002\035\022\033/api/currency/v1/currencies'
  _CURRENCYSERVICE.methods_by_name['GetCurrency']._options = None
  _CURRENCYSERVICE.methods_by_name['GetCurrency']._serialized_options = b'\202\323\344\223\002\"\022 /api/currency/v1/currencies/{id}'
  _CURRENCYSERVICE.methods_by_name['GetDefaultCurrency']._options = None
  _CURRENCYSERVICE.methods_by_name['GetDefaultCurrency']._serialized_options = b'\202\323\344\223\002#\022!/api/currency/v1/default-currency'
  _CURRENCY._serialized_start=112
  _CURRENCY._serialized_end=184
  _CURRENCYLIST._serialized_start=186
  _CURRENCYLIST._serialized_end=253
  _GETDEFAULTCURRENCYREQUEST._serialized_start=255
  _GETDEFAULTCURRENCYREQUEST._serialized_end=307
  _CURRENCYSERVICE._serialized_start=310
  _CURRENCYSERVICE._serialized_end=879
# @@protoc_insertion_point(module_scope)
