# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth/v1/auth.proto\x12\x16\x61rangodb.cloud.auth.v1\x1a\x16\x63ommon/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"T\n\x10\x41uthorizeRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61llback_url\x18\x03 \x01(\t2\xfc\x01\n\x0b\x41uthService\x12u\n\rGetAPIVersion\x12\x1f.arangodb.cloud.common.v1.Empty\x1a!.arangodb.cloud.common.v1.Version\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/auth/v1/api-version\x12v\n\tAuthorize\x12(.arangodb.cloud.auth.v1.AuthorizeRequest\x1a\x1f.arangodb.cloud.common.v1.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/api/auth/v1/authorizeB*Z(github.com/arangodb-managed/apis/auth/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/arangodb-managed/apis/auth/v1'
  _AUTHSERVICE.methods_by_name['GetAPIVersion']._options = None
  _AUTHSERVICE.methods_by_name['GetAPIVersion']._serialized_options = b'\202\323\344\223\002\032\022\030/api/auth/v1/api-version'
  _AUTHSERVICE.methods_by_name['Authorize']._options = None
  _AUTHSERVICE.methods_by_name['Authorize']._serialized_options = b'\202\323\344\223\002\030\"\026/api/auth/v1/authorize'
  _AUTHORIZEREQUEST._serialized_start=100
  _AUTHORIZEREQUEST._serialized_end=184
  _AUTHSERVICE._serialized_start=187
  _AUTHSERVICE._serialized_end=439
# @@protoc_insertion_point(module_scope)
