# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\x18\x61rangodb.cloud.common.v1\"\x07\n\x05\x45mpty\"B\n\x0bListOptions\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x03\x12\x12\n\ncontext_id\x18\x03 \x01(\t\"\x17\n\tIDOptions\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\nURLOptions\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x19\n\x07YesOrNo\x12\x0e\n\x06result\x18\x01 \x01(\x08\"<\n\x06\x42udget\x12\x0c\n\x04used\x18\x01 \x01(\x03\x12\x11\n\tavailable\x18\x02 \x01(\x03\x12\x11\n\tunlimited\x18\x03 \x01(\x08\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\x42,Z*github.com/arangodb-managed/apis/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/arangodb-managed/apis/common/v1'
  _EMPTY._serialized_start=52
  _EMPTY._serialized_end=59
  _LISTOPTIONS._serialized_start=61
  _LISTOPTIONS._serialized_end=127
  _IDOPTIONS._serialized_start=129
  _IDOPTIONS._serialized_end=152
  _URLOPTIONS._serialized_start=154
  _URLOPTIONS._serialized_end=179
  _YESORNO._serialized_start=181
  _YESORNO._serialized_end=206
  _BUDGET._serialized_start=208
  _BUDGET._serialized_end=268
  _VERSION._serialized_start=270
  _VERSION._serialized_end=324
# @@protoc_insertion_point(module_scope)
