# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data-service/v1/dataservice.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'data-service/v1/dataservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from data.v1 import data_pb2 as data_dot_v1_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!data-service/v1/dataservice.proto\x12+arangodb.cloud.integration.bucketservice.v1\x1a\x16\x63ommon/v1/common.proto\x1a\x12\x64\x61ta/v1/data.proto2\x81\x01\n\x0b\x44\x61taService\x12r\n\x1cGetDeploymentRootCredentials\x12#.arangodb.cloud.common.v1.IDOptions\x1a-.arangodb.cloud.data.v1.DeploymentCredentialsB@Z>github.com/arangodb-managed/integration-apis/bucket-service/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service.v1.dataservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/arangodb-managed/integration-apis/bucket-service/v1'
  _globals['_DATASERVICE']._serialized_start=127
  _globals['_DATASERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
