# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from data.v1 import data_pb2 as data_dot_v1_dot_data__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in data_service/v1/dataservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """DataService is the API used to manage deployments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeploymentRootCredentials = channel.unary_unary(
                '/arangodb.cloud.integration.bucketservice.v1.DataService/GetDeploymentRootCredentials',
                request_serializer=common_dot_v1_dot_common__pb2.IDOptions.SerializeToString,
                response_deserializer=data_dot_v1_dot_data__pb2.DeploymentCredentials.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """DataService is the API used to manage deployments.
    """

    def GetDeploymentRootCredentials(self, request, context):
        """Fetch the credentials for the root user of the deployment with given ID.
        When the integration sidecar is running in the context of a single deployment, the provided ID is optional, however if provided it should match.
        Required permissions:
        - dataservice.deployment.get-root-credentials for the deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeploymentRootCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentRootCredentials,
                    request_deserializer=common_dot_v1_dot_common__pb2.IDOptions.FromString,
                    response_serializer=data_dot_v1_dot_data__pb2.DeploymentCredentials.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arangodb.cloud.integration.bucketservice.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arangodb.cloud.integration.bucketservice.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """DataService is the API used to manage deployments.
    """

    @staticmethod
    def GetDeploymentRootCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arangodb.cloud.integration.bucketservice.v1.DataService/GetDeploymentRootCredentials',
            common_dot_v1_dot_common__pb2.IDOptions.SerializeToString,
            data_dot_v1_dot_data__pb2.DeploymentCredentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
