# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml/v1/ml.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from github.com.golang.protobuf.ptypes.timestamp import timestamp_pb2 as github_dot_com_dot_golang_dot_protobuf_dot_ptypes_dot_timestamp_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eml/v1/ml.proto\x12\x14\x61rangodb.cloud.ml.v1\x1a\x16\x63ommon/v1/common.proto\x1a;github.com/golang/protobuf/ptypes/timestamp/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"b\n\nMLServices\x12\x15\n\rdeployment_id\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12,\n\x06status\x18\x64 \x01(\x0b\x32\x1c.arangodb.cloud.ml.v1.Status\"\x94\x01\n\x06Status\x12\r\n\x05phase\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x33\n\x0flast_updated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x08services\x18\x04 \x03(\x0b\x32#.arangodb.cloud.ml.v1.ServiceStatus\"\xfb\x01\n\rServiceStatus\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tavailable\x18\x02 \x01(\x08\x12\x0e\n\x06\x66\x61iled\x18\x03 \x01(\x08\x12\x38\n\x05usage\x18\x04 \x01(\x0b\x32).arangodb.cloud.ml.v1.ServiceStatus.Usage\x12\x10\n\x08replicas\x18\x05 \x01(\x05\x1am\n\x05Usage\x12\x19\n\x11last_memory_usage\x18\x01 \x01(\x03\x12\x16\n\x0elast_cpu_usage\x18\x02 \x01(\x02\x12\x19\n\x11last_memory_limit\x18\x03 \x01(\x03\x12\x16\n\x0elast_cpu_limit\x18\x04 \x01(\x02\x32\x87\x03\n\tMLService\x12s\n\rGetAPIVersion\x12\x1f.arangodb.cloud.common.v1.Empty\x1a!.arangodb.cloud.common.v1.Version\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/ml/v1/api-version\x12z\n\rGetMLServices\x12#.arangodb.cloud.common.v1.IDOptions\x1a .arangodb.cloud.ml.v1.MLServices\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/ml/v1/mlservices/{id}\x12\x88\x01\n\x10UpdateMLServices\x12 .arangodb.cloud.ml.v1.MLServices\x1a .arangodb.cloud.ml.v1.MLServices\"0\x82\xd3\xe4\x93\x02*\x1a%/api/ml/v1/mlservices/{deployment_id}:\x01*B(Z&github.com/arangodb-managed/apis/ml/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml.v1.ml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/arangodb-managed/apis/ml/v1'
  _MLSERVICE.methods_by_name['GetAPIVersion']._options = None
  _MLSERVICE.methods_by_name['GetAPIVersion']._serialized_options = b'\202\323\344\223\002\030\022\026/api/ml/v1/api-version'
  _MLSERVICE.methods_by_name['GetMLServices']._options = None
  _MLSERVICE.methods_by_name['GetMLServices']._serialized_options = b'\202\323\344\223\002\034\022\032/api/ml/v1/mlservices/{id}'
  _MLSERVICE.methods_by_name['UpdateMLServices']._options = None
  _MLSERVICE.methods_by_name['UpdateMLServices']._serialized_options = b'\202\323\344\223\002*\032%/api/ml/v1/mlservices/{deployment_id}:\001*'
  _globals['_MLSERVICES']._serialized_start=155
  _globals['_MLSERVICES']._serialized_end=253
  _globals['_STATUS']._serialized_start=256
  _globals['_STATUS']._serialized_end=404
  _globals['_SERVICESTATUS']._serialized_start=407
  _globals['_SERVICESTATUS']._serialized_end=658
  _globals['_SERVICESTATUS_USAGE']._serialized_start=549
  _globals['_SERVICESTATUS_USAGE']._serialized_end=658
  _globals['_MLSERVICE']._serialized_start=661
  _globals['_MLSERVICE']._serialized_end=1052
# @@protoc_insertion_point(module_scope)
