# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from ml.v1 import ml_pb2 as ml_dot_v1_dot_ml__pb2


class MLServiceStub(object):
    """MLService is the API used to configure ArangoML on ArangoGraph Insights Platform.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAPIVersion = channel.unary_unary(
                '/arangodb.cloud.ml.v1.MLService/GetAPIVersion',
                request_serializer=common_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Version.FromString,
                )
        self.GetMLServices = channel.unary_unary(
                '/arangodb.cloud.ml.v1.MLService/GetMLServices',
                request_serializer=common_dot_v1_dot_common__pb2.IDOptions.SerializeToString,
                response_deserializer=ml_dot_v1_dot_ml__pb2.MLServices.FromString,
                )
        self.UpdateMLServices = channel.unary_unary(
                '/arangodb.cloud.ml.v1.MLService/UpdateMLServices',
                request_serializer=ml_dot_v1_dot_ml__pb2.MLServices.SerializeToString,
                response_deserializer=ml_dot_v1_dot_ml__pb2.MLServices.FromString,
                )


class MLServiceServicer(object):
    """MLService is the API used to configure ArangoML on ArangoGraph Insights Platform.
    """

    def GetAPIVersion(self, request, context):
        """Get the current API version of this service.
        Required permissions:
        - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMLServices(self, request, context):
        """Get an existing MLServices resource for a given deployment (specified by the id). 
        Required permissions:
        - ml.mlservices.get
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMLServices(self, request, context):
        """Update an existing MLServices resource. If it does not exist, this will create a new one.
        Pass the desired updated state of MLServices to this call.
        Required permissions:
        - ml.mlservices.update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAPIVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPIVersion,
                    request_deserializer=common_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Version.SerializeToString,
            ),
            'GetMLServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMLServices,
                    request_deserializer=common_dot_v1_dot_common__pb2.IDOptions.FromString,
                    response_serializer=ml_dot_v1_dot_ml__pb2.MLServices.SerializeToString,
            ),
            'UpdateMLServices': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMLServices,
                    request_deserializer=ml_dot_v1_dot_ml__pb2.MLServices.FromString,
                    response_serializer=ml_dot_v1_dot_ml__pb2.MLServices.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arangodb.cloud.ml.v1.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """MLService is the API used to configure ArangoML on ArangoGraph Insights Platform.
    """

    @staticmethod
    def GetAPIVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.ml.v1.MLService/GetAPIVersion',
            common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            common_dot_v1_dot_common__pb2.Version.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMLServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.ml.v1.MLService/GetMLServices',
            common_dot_v1_dot_common__pb2.IDOptions.SerializeToString,
            ml_dot_v1_dot_ml__pb2.MLServices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMLServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.ml.v1.MLService/UpdateMLServices',
            ml_dot_v1_dot_ml__pb2.MLServices.SerializeToString,
            ml_dot_v1_dot_ml__pb2.MLServices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
