//
// This file is AUTO-GENERATED by protoc-gen-ts.
// Do not modify it manually.
///
import api from '../../api'
import * as googleTypes from '../../googleTypes'

// File: common/v1/icommon.proto
// Package: arangodb.cloud.integration.common.v1

// KeyValuePair specifies a key-value pair.
export interface KeyValuePair {
  // The key.
  // string
  key?: string;
  
  // The value.
  // string
  value?: string;
}
