# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from deployment_profile.v1 import deploymentprofile_pb2 as deployment__profile_dot_v1_dot_deploymentprofile__pb2


class DeploymentProfileServiceStub(object):
    """Deployment Profile service is used to manage Deployment Profiles.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAPIVersion = channel.unary_unary(
                '/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/GetAPIVersion',
                request_serializer=common_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Version.FromString,
                )
        self.ListDeploymentProfiles = channel.unary_unary(
                '/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/ListDeploymentProfiles',
                request_serializer=deployment__profile_dot_v1_dot_deploymentprofile__pb2.ListDeploymentProfilesRequest.SerializeToString,
                response_deserializer=deployment__profile_dot_v1_dot_deploymentprofile__pb2.DeploymentProfileList.FromString,
                )


class DeploymentProfileServiceServicer(object):
    """Deployment Profile service is used to manage Deployment Profiles.
    """

    def GetAPIVersion(self, request, context):
        """Get the current API version of this service.
        Required permissions:
        - None (authenticated only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeploymentProfiles(self, request, context):
        """List all deployment profiles for the organization identified by the given organization identifier.
        Required permissions:
        - deploymentprofile.deploymentprofile.list on the organization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeploymentProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAPIVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAPIVersion,
                    request_deserializer=common_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Version.SerializeToString,
            ),
            'ListDeploymentProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeploymentProfiles,
                    request_deserializer=deployment__profile_dot_v1_dot_deploymentprofile__pb2.ListDeploymentProfilesRequest.FromString,
                    response_serializer=deployment__profile_dot_v1_dot_deploymentprofile__pb2.DeploymentProfileList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arangodb.cloud.deploymentprofile.v1.DeploymentProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeploymentProfileService(object):
    """Deployment Profile service is used to manage Deployment Profiles.
    """

    @staticmethod
    def GetAPIVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/GetAPIVersion',
            common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            common_dot_v1_dot_common__pb2.Version.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDeploymentProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arangodb.cloud.deploymentprofile.v1.DeploymentProfileService/ListDeploymentProfiles',
            deployment__profile_dot_v1_dot_deploymentprofile__pb2.ListDeploymentProfilesRequest.SerializeToString,
            deployment__profile_dot_v1_dot_deploymentprofile__pb2.DeploymentProfileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
